In [16]:
import pandas as pd

# Load the dataset from a JSON URL into a pandas DataFrame
amazon_one_plus_reviews_db = pd.read_json('https://query.data.world/s/eke656w4udxnc6v57negepzxrddrzw?dws=00000')

# List the columns of the DataFrame to understand its structure
list(amazon_one_plus_reviews_db.columns)

['product',
 'product_company',
 'profile_name',
 'review_title',
 'review_rating',
 'review_text',
 'helpful_count',
 'total_comments',
 'review_country',
 'reviewed_at',
 'url',
 'crawled_at',
 '_id',
 'verified_purchase',
 'color',
 'style_name',
 'size_name',
 'category',
 'sub_category',
 'images']

In [17]:
# Drop columns that are not needed for analysis to simplify the DataFrame
amazon_one_plus_reviews_db.drop([
    'profile_name',
    'total_comments',
    'url',
    'crawled_at',
    '_id',
    'color',
    'style_name',
    'images',
    'size_name'
  ], axis=1, inplace=True)

amazon_one_plus_reviews_db

,product,product_company,review_title,review_rating,review_text,helpful_count,review_country,reviewed_at,verified_purchase,category,sub_category
0,"OnePlus Nord 5G (Gray Onyx, 8GB RAM, 128GB Sto...",OnePlus,*Read before you buy!!*,5.0 out of 5 stars,"\n Yea..pre-ordered on 28 July, got it on 4 A...",721 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
1,"OnePlus Nord 5G (Gray Onyx, 8GB RAM, 128GB Sto...",OnePlus,Near to mid range Perfection,5.0 out of 5 stars,"\n Got it delivered yesterday , used for abou...",436 people found this helpful,India,2020-08-03,Verified Purchase,electronics,mobiles
2,"OnePlus Nord 5G (Gray Onyx, 8GB RAM, 128GB Sto...",OnePlus,Great price!,5.0 out of 5 stars,\n An amazing phone!,322 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
3,"OnePlus Nord 5G (Gray Onyx, 8GB RAM, 128GB Sto...",OnePlus,Beast in OnePlus.,5.0 out of 5 stars,\n Brilliant..,243 people found this helpful,India,2020-08-02,Verified Purchase,electronics,mobiles
4,"OnePlus Nord 5G (Gray Onyx, 8GB RAM, 128GB Sto...",OnePlus,Changed to Nord from 6t,5.0 out of 5 stars,\n I was skeptical about changing from One pl...,109 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
...,...,...,...,...,...,...,...,...,...,...,...
30607,"Redmi Note 9 Pro (Aurora Blue, 4GB RAM, 64GB S...",Redmi,Great but not satisfied for me,2.0 out of 5 stars,\n Quality of phone is great but from my pers...,0,India,2020-09-03,Verified Purchase,electronics,mobiles
30608,"Redmi Note 9 Pro (Aurora Blue, 4GB RAM, 64GB S...",Redmi,Not recommend,2.0 out of 5 stars,\n Not recommend\n,0,India,2020-05-20,Verified Purchase,electronics,mobiles
30609,"Redmi Note 9 Pro (Aurora Blue, 4GB RAM, 64GB S...",Redmi,WORST MARKETING TACTICS OF FLASH SALE OF REDMI...,2.0 out of 5 stars,\n Redmi and Amazon is engaged in a worst mar...,3 people found this helpful,India,2020-06-29,na,electronics,mobiles
30610,"Redmi Note 9 Pro (Aurora Blue, 4GB RAM, 64GB S...",Redmi,Display retention issue,2.0 out of 5 stars,"\n I am facing display retention problem, aft...",0,India,2020-04-26,na,electronics,mobiles
30611,"Redmi Note 9 Pro (Aurora Blue, 4GB RAM, 64GB S...",Redmi,Camera quality is bad 👎,2.0 out of 5 stars,\n Front camera quality is worse as compare t...,0,India,2020-07-05,Verified Purchase,electronics,mobiles

In [18]:
# Check for any null values in each column to ensure data quality
for column_name in amazon_one_plus_reviews_db.columns.tolist():
  print(amazon_one_plus_reviews_db[column_name].isnull().any())

False
False
False
False
False
False
False
False
False
False
False

In [19]:
# Clean the 'product' column by removing any text after '(' to standardize product names
for i in range(len(amazon_one_plus_reviews_db['product'])):
  amazon_one_plus_reviews_db['product'][i] = amazon_one_plus_reviews_db['product'][i].split('(')[0]

amazon_one_plus_reviews_db

<ipython-input-19-bfea1d4afb0b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  amazon_one_plus_reviews_db['product'][i] = amazon_one_plus_reviews_db['product'][i].split('(')[0]

,product,product_company,review_title,review_rating,review_text,helpful_count,review_country,reviewed_at,verified_purchase,category,sub_category
0,OnePlus Nord 5G,OnePlus,*Read before you buy!!*,5.0 out of 5 stars,"\n Yea..pre-ordered on 28 July, got it on 4 A...",721 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
1,OnePlus Nord 5G,OnePlus,Near to mid range Perfection,5.0 out of 5 stars,"\n Got it delivered yesterday , used for abou...",436 people found this helpful,India,2020-08-03,Verified Purchase,electronics,mobiles
2,OnePlus Nord 5G,OnePlus,Great price!,5.0 out of 5 stars,\n An amazing phone!,322 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
3,OnePlus Nord 5G,OnePlus,Beast in OnePlus.,5.0 out of 5 stars,\n Brilliant..,243 people found this helpful,India,2020-08-02,Verified Purchase,electronics,mobiles
4,OnePlus Nord 5G,OnePlus,Changed to Nord from 6t,5.0 out of 5 stars,\n I was skeptical about changing from One pl...,109 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
...,...,...,...,...,...,...,...,...,...,...,...
30607,Redmi Note 9 Pro,Redmi,Great but not satisfied for me,2.0 out of 5 stars,\n Quality of phone is great but from my pers...,0,India,2020-09-03,Verified Purchase,electronics,mobiles
30608,Redmi Note 9 Pro,Redmi,Not recommend,2.0 out of 5 stars,\n Not recommend\n,0,India,2020-05-20,Verified Purchase,electronics,mobiles
30609,Redmi Note 9 Pro,Redmi,WORST MARKETING TACTICS OF FLASH SALE OF REDMI...,2.0 out of 5 stars,\n Redmi and Amazon is engaged in a worst mar...,3 people found this helpful,India,2020-06-29,na,electronics,mobiles
30610,Redmi Note 9 Pro,Redmi,Display retention issue,2.0 out of 5 stars,"\n I am facing display retention problem, aft...",0,India,2020-04-26,na,electronics,mobiles
30611,Redmi Note 9 Pro,Redmi,Camera quality is bad 👎,2.0 out of 5 stars,\n Front camera quality is worse as compare t...,0,India,2020-07-05,Verified Purchase,electronics,mobiles

In [20]:
# Trim leading and trailing whitespace from 'review_title' column values
for i in range(len(amazon_one_plus_reviews_db['review_title'])):
  amazon_one_plus_reviews_db['review_title'][i] = amazon_one_plus_reviews_db['review_title'][i].strip()

amazon_one_plus_reviews_db

<ipython-input-20-9481507a4bba>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  amazon_one_plus_reviews_db['review_title'][i] = amazon_one_plus_reviews_db['review_title'][i].strip()

,product,product_company,review_title,review_rating,review_text,helpful_count,review_country,reviewed_at,verified_purchase,category,sub_category
0,OnePlus Nord 5G,OnePlus,*Read before you buy!!*,5.0 out of 5 stars,"\n Yea..pre-ordered on 28 July, got it on 4 A...",721 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
1,OnePlus Nord 5G,OnePlus,Near to mid range Perfection,5.0 out of 5 stars,"\n Got it delivered yesterday , used for abou...",436 people found this helpful,India,2020-08-03,Verified Purchase,electronics,mobiles
2,OnePlus Nord 5G,OnePlus,Great price!,5.0 out of 5 stars,\n An amazing phone!,322 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
3,OnePlus Nord 5G,OnePlus,Beast in OnePlus.,5.0 out of 5 stars,\n Brilliant..,243 people found this helpful,India,2020-08-02,Verified Purchase,electronics,mobiles
4,OnePlus Nord 5G,OnePlus,Changed to Nord from 6t,5.0 out of 5 stars,\n I was skeptical about changing from One pl...,109 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
...,...,...,...,...,...,...,...,...,...,...,...
30607,Redmi Note 9 Pro,Redmi,Great but not satisfied for me,2.0 out of 5 stars,\n Quality of phone is great but from my pers...,0,India,2020-09-03,Verified Purchase,electronics,mobiles
30608,Redmi Note 9 Pro,Redmi,Not recommend,2.0 out of 5 stars,\n Not recommend\n,0,India,2020-05-20,Verified Purchase,electronics,mobiles
30609,Redmi Note 9 Pro,Redmi,WORST MARKETING TACTICS OF FLASH SALE OF REDMI...,2.0 out of 5 stars,\n Redmi and Amazon is engaged in a worst mar...,3 people found this helpful,India,2020-06-29,na,electronics,mobiles
30610,Redmi Note 9 Pro,Redmi,Display retention issue,2.0 out of 5 stars,"\n I am facing display retention problem, aft...",0,India,2020-04-26,na,electronics,mobiles
30611,Redmi Note 9 Pro,Redmi,Camera quality is bad 👎,2.0 out of 5 stars,\n Front camera quality is worse as compare t...,0,India,2020-07-05,Verified Purchase,electronics,mobiles

In [21]:
# Convert 'review_rating' from string to float, keeping only the numeric part before "out"
for i in range(len(amazon_one_plus_reviews_db['review_rating'])):
  amazon_one_plus_reviews_db['review_rating'][i] = float(amazon_one_plus_reviews_db['review_rating'][i].split('out')[0])

# Ensure 'review_rating' column is of float type
amazon_one_plus_reviews_db['review_rating'] = amazon_one_plus_reviews_db['review_rating'].astype(float)

amazon_one_plus_reviews_db

<ipython-input-21-236243c8fb6b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  amazon_one_plus_reviews_db['review_rating'][i] = float(amazon_one_plus_reviews_db['review_rating'][i].split('out')[0])

,product,product_company,review_title,review_rating,review_text,helpful_count,review_country,reviewed_at,verified_purchase,category,sub_category
0,OnePlus Nord 5G,OnePlus,*Read before you buy!!*,5.0,"\n Yea..pre-ordered on 28 July, got it on 4 A...",721 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
1,OnePlus Nord 5G,OnePlus,Near to mid range Perfection,5.0,"\n Got it delivered yesterday , used for abou...",436 people found this helpful,India,2020-08-03,Verified Purchase,electronics,mobiles
2,OnePlus Nord 5G,OnePlus,Great price!,5.0,\n An amazing phone!,322 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
3,OnePlus Nord 5G,OnePlus,Beast in OnePlus.,5.0,\n Brilliant..,243 people found this helpful,India,2020-08-02,Verified Purchase,electronics,mobiles
4,OnePlus Nord 5G,OnePlus,Changed to Nord from 6t,5.0,\n I was skeptical about changing from One pl...,109 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
...,...,...,...,...,...,...,...,...,...,...,...
30607,Redmi Note 9 Pro,Redmi,Great but not satisfied for me,2.0,\n Quality of phone is great but from my pers...,0,India,2020-09-03,Verified Purchase,electronics,mobiles
30608,Redmi Note 9 Pro,Redmi,Not recommend,2.0,\n Not recommend\n,0,India,2020-05-20,Verified Purchase,electronics,mobiles
30609,Redmi Note 9 Pro,Redmi,WORST MARKETING TACTICS OF FLASH SALE OF REDMI...,2.0,\n Redmi and Amazon is engaged in a worst mar...,3 people found this helpful,India,2020-06-29,na,electronics,mobiles
30610,Redmi Note 9 Pro,Redmi,Display retention issue,2.0,"\n I am facing display retention problem, aft...",0,India,2020-04-26,na,electronics,mobiles
30611,Redmi Note 9 Pro,Redmi,Camera quality is bad 👎,2.0,\n Front camera quality is worse as compare t...,0,India,2020-07-05,Verified Purchase,electronics,mobiles

In [22]:
# Remove newline characters from 'review_text' to clean the text
for i in range(len(amazon_one_plus_reviews_db['review_text'])):
  amazon_one_plus_reviews_db['review_text'][i] = amazon_one_plus_reviews_db['review_text'][i].replace('\n', '')

amazon_one_plus_reviews_db

<ipython-input-22-87c1c8b9efdf>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  amazon_one_plus_reviews_db['review_text'][i] = amazon_one_plus_reviews_db['review_text'][i].replace('\n', '')

,product,product_company,review_title,review_rating,review_text,helpful_count,review_country,reviewed_at,verified_purchase,category,sub_category
0,OnePlus Nord 5G,OnePlus,*Read before you buy!!*,5.0,"Yea..pre-ordered on 28 July, got it on 4 Aug...",721 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
1,OnePlus Nord 5G,OnePlus,Near to mid range Perfection,5.0,"Got it delivered yesterday , used for about ...",436 people found this helpful,India,2020-08-03,Verified Purchase,electronics,mobiles
2,OnePlus Nord 5G,OnePlus,Great price!,5.0,An amazing phone!,322 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
3,OnePlus Nord 5G,OnePlus,Beast in OnePlus.,5.0,Brilliant..,243 people found this helpful,India,2020-08-02,Verified Purchase,electronics,mobiles
4,OnePlus Nord 5G,OnePlus,Changed to Nord from 6t,5.0,I was skeptical about changing from One plus...,109 people found this helpful,India,2020-08-04,Verified Purchase,electronics,mobiles
...,...,...,...,...,...,...,...,...,...,...,...
30607,Redmi Note 9 Pro,Redmi,Great but not satisfied for me,2.0,Quality of phone is great but from my perspe...,0,India,2020-09-03,Verified Purchase,electronics,mobiles
30608,Redmi Note 9 Pro,Redmi,Not recommend,2.0,Not recommend,0,India,2020-05-20,Verified Purchase,electronics,mobiles
30609,Redmi Note 9 Pro,Redmi,WORST MARKETING TACTICS OF FLASH SALE OF REDMI...,2.0,Redmi and Amazon is engaged in a worst marke...,3 people found this helpful,India,2020-06-29,na,electronics,mobiles
30610,Redmi Note 9 Pro,Redmi,Display retention issue,2.0,"I am facing display retention problem, after...",0,India,2020-04-26,na,electronics,mobiles
30611,Redmi Note 9 Pro,Redmi,Camera quality is bad 👎,2.0,Front camera quality is worse as compare to ...,0,India,2020-07-05,Verified Purchase,electronics,mobiles

In [23]:
# Install the word2number package, required for converting textual number expressions to numeric form
!pip install word2number

Requirement already satisfied: word2number in /usr/local/lib/python3.10/dist-packages (1.1)

In [24]:
from word2number import w2n

# Clean 'helpful_count' by converting word-based numbers and removing commas
for i in range(len(amazon_one_plus_reviews_db['helpful_count'])):
  new_value = amazon_one_plus_reviews_db['helpful_count'][i].split()[0].replace(',', '')

  try: # First, try to convert directly to int
      new_value = int(new_value)

  except ValueError: # If direct conversion fails, try to convert from words

      try:
          new_value = w2n.word_to_num(new_value)

      except ValueError: # If both conversions fail, assign NA
          new_value = pd.NA

  amazon_one_plus_reviews_db['helpful_count'][i] = new_value

# Ensure 'helpful_count' column is of integer type
amazon_one_plus_reviews_db['helpful_count'] = amazon_one_plus_reviews_db['helpful_count'].astype(int)

amazon_one_plus_reviews_db

<ipython-input-24-531ac6c49443>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  amazon_one_plus_reviews_db['helpful_count'][i] = new_value

,product,product_company,review_title,review_rating,review_text,helpful_count,review_country,reviewed_at,verified_purchase,category,sub_category
0,OnePlus Nord 5G,OnePlus,*Read before you buy!!*,5.0,"Yea..pre-ordered on 28 July, got it on 4 Aug...",721,India,2020-08-04,Verified Purchase,electronics,mobiles
1,OnePlus Nord 5G,OnePlus,Near to mid range Perfection,5.0,"Got it delivered yesterday , used for about ...",436,India,2020-08-03,Verified Purchase,electronics,mobiles
2,OnePlus Nord 5G,OnePlus,Great price!,5.0,An amazing phone!,322,India,2020-08-04,Verified Purchase,electronics,mobiles
3,OnePlus Nord 5G,OnePlus,Beast in OnePlus.,5.0,Brilliant..,243,India,2020-08-02,Verified Purchase,electronics,mobiles
4,OnePlus Nord 5G,OnePlus,Changed to Nord from 6t,5.0,I was skeptical about changing from One plus...,109,India,2020-08-04,Verified Purchase,electronics,mobiles
...,...,...,...,...,...,...,...,...,...,...,...
30607,Redmi Note 9 Pro,Redmi,Great but not satisfied for me,2.0,Quality of phone is great but from my perspe...,0,India,2020-09-03,Verified Purchase,electronics,mobiles
30608,Redmi Note 9 Pro,Redmi,Not recommend,2.0,Not recommend,0,India,2020-05-20,Verified Purchase,electronics,mobiles
30609,Redmi Note 9 Pro,Redmi,WORST MARKETING TACTICS OF FLASH SALE OF REDMI...,2.0,Redmi and Amazon is engaged in a worst marke...,3,India,2020-06-29,na,electronics,mobiles
30610,Redmi Note 9 Pro,Redmi,Display retention issue,2.0,"I am facing display retention problem, after...",0,India,2020-04-26,na,electronics,mobiles
30611,Redmi Note 9 Pro,Redmi,Camera quality is bad 👎,2.0,Front camera quality is worse as compare to ...,0,India,2020-07-05,Verified Purchase,electronics,mobiles

In [25]:
# Trim whitespace from 'review_country' values
for i in range(len(amazon_one_plus_reviews_db['review_country'])):
  amazon_one_plus_reviews_db['review_country'][i] = amazon_one_plus_reviews_db['review_country'][i].strip()

amazon_one_plus_reviews_db

<ipython-input-25-d33a8f408f29>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  amazon_one_plus_reviews_db['review_country'][i] = amazon_one_plus_reviews_db['review_country'][i].strip()

,product,product_company,review_title,review_rating,review_text,helpful_count,review_country,reviewed_at,verified_purchase,category,sub_category
0,OnePlus Nord 5G,OnePlus,*Read before you buy!!*,5.0,"Yea..pre-ordered on 28 July, got it on 4 Aug...",721,India,2020-08-04,Verified Purchase,electronics,mobiles
1,OnePlus Nord 5G,OnePlus,Near to mid range Perfection,5.0,"Got it delivered yesterday , used for about ...",436,India,2020-08-03,Verified Purchase,electronics,mobiles
2,OnePlus Nord 5G,OnePlus,Great price!,5.0,An amazing phone!,322,India,2020-08-04,Verified Purchase,electronics,mobiles
3,OnePlus Nord 5G,OnePlus,Beast in OnePlus.,5.0,Brilliant..,243,India,2020-08-02,Verified Purchase,electronics,mobiles
4,OnePlus Nord 5G,OnePlus,Changed to Nord from 6t,5.0,I was skeptical about changing from One plus...,109,India,2020-08-04,Verified Purchase,electronics,mobiles
...,...,...,...,...,...,...,...,...,...,...,...
30607,Redmi Note 9 Pro,Redmi,Great but not satisfied for me,2.0,Quality of phone is great but from my perspe...,0,India,2020-09-03,Verified Purchase,electronics,mobiles
30608,Redmi Note 9 Pro,Redmi,Not recommend,2.0,Not recommend,0,India,2020-05-20,Verified Purchase,electronics,mobiles
30609,Redmi Note 9 Pro,Redmi,WORST MARKETING TACTICS OF FLASH SALE OF REDMI...,2.0,Redmi and Amazon is engaged in a worst marke...,3,India,2020-06-29,na,electronics,mobiles
30610,Redmi Note 9 Pro,Redmi,Display retention issue,2.0,"I am facing display retention problem, after...",0,India,2020-04-26,na,electronics,mobiles
30611,Redmi Note 9 Pro,Redmi,Camera quality is bad 👎,2.0,Front camera quality is worse as compare to ...,0,India,2020-07-05,Verified Purchase,electronics,mobiles

In [26]:
# Convert 'verified_purchase' from string to binary numeric values, where 'na' becomes 0 and all other values become 1
for i in range(len(amazon_one_plus_reviews_db['verified_purchase'])):
  current_value = amazon_one_plus_reviews_db['verified_purchase'][i]

  if current_value == 'na':
    amazon_one_plus_reviews_db['verified_purchase'][i] = 0
  else:
    amazon_one_plus_reviews_db['verified_purchase'][i] = 1

# Ensure 'verified_purchase' column is of integer type
amazon_one_plus_reviews_db['verified_purchase'] = amazon_one_plus_reviews_db['verified_purchase'].astype(int)

amazon_one_plus_reviews_db

<ipython-input-26-0d630dcb541c>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  amazon_one_plus_reviews_db['verified_purchase'][i] = 1
<ipython-input-26-0d630dcb541c>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  amazon_one_plus_reviews_db['verified_purchase'][i] = 0

,product,product_company,review_title,review_rating,review_text,helpful_count,review_country,reviewed_at,verified_purchase,category,sub_category
0,OnePlus Nord 5G,OnePlus,*Read before you buy!!*,5.0,"Yea..pre-ordered on 28 July, got it on 4 Aug...",721,India,2020-08-04,1,electronics,mobiles
1,OnePlus Nord 5G,OnePlus,Near to mid range Perfection,5.0,"Got it delivered yesterday , used for about ...",436,India,2020-08-03,1,electronics,mobiles
2,OnePlus Nord 5G,OnePlus,Great price!,5.0,An amazing phone!,322,India,2020-08-04,1,electronics,mobiles
3,OnePlus Nord 5G,OnePlus,Beast in OnePlus.,5.0,Brilliant..,243,India,2020-08-02,1,electronics,mobiles
4,OnePlus Nord 5G,OnePlus,Changed to Nord from 6t,5.0,I was skeptical about changing from One plus...,109,India,2020-08-04,1,electronics,mobiles
...,...,...,...,...,...,...,...,...,...,...,...
30607,Redmi Note 9 Pro,Redmi,Great but not satisfied for me,2.0,Quality of phone is great but from my perspe...,0,India,2020-09-03,1,electronics,mobiles
30608,Redmi Note 9 Pro,Redmi,Not recommend,2.0,Not recommend,0,India,2020-05-20,1,electronics,mobiles
30609,Redmi Note 9 Pro,Redmi,WORST MARKETING TACTICS OF FLASH SALE OF REDMI...,2.0,Redmi and Amazon is engaged in a worst marke...,3,India,2020-06-29,0,electronics,mobiles
30610,Redmi Note 9 Pro,Redmi,Display retention issue,2.0,"I am facing display retention problem, after...",0,India,2020-04-26,0,electronics,mobiles
30611,Redmi Note 9 Pro,Redmi,Camera quality is bad 👎,2.0,Front camera quality is worse as compare to ...,0,India,2020-07-05,1,electronics,mobiles

In [27]:
# Check data types of all columns for confirmation
amazon_one_plus_reviews_db.dtypes

product                      object
product_company              object
review_title                 object
review_rating               float64
review_text                  object
helpful_count                 int64
review_country               object
reviewed_at          datetime64[ns]
verified_purchase             int64
category                     object
sub_category                 object
dtype: object

In [28]:
# Combine 'review_title' and 'review_text' into a single 'review_description' column, formatted with tags <t> for 'title' and <b> for 'body'
review_descripiton = []
for i in range(len(amazon_one_plus_reviews_db['review_title'])):
  review_title_elem = amazon_one_plus_reviews_db['review_title'][i]
  review_text_elem = amazon_one_plus_reviews_db['review_text'][i]
  new_elem = f'<t>{review_title_elem}</t><b>{review_text_elem}</b>' # t -> title | b -> body
  review_descripiton.append(new_elem)

amazon_one_plus_reviews_db['review_descripiton'] = review_descripiton

# Drop the now redundant 'review_title' and 'review_text' columns
amazon_one_plus_reviews_db.drop(['review_title', 'review_text'], axis=1, inplace=True)

amazon_one_plus_reviews_db

,product,product_company,review_rating,helpful_count,review_country,reviewed_at,verified_purchase,category,sub_category,review_descripiton
0,OnePlus Nord 5G,OnePlus,5.0,721,India,2020-08-04,1,electronics,mobiles,<t>*Read before you buy!!*</t><b> Yea..pre-or...
1,OnePlus Nord 5G,OnePlus,5.0,436,India,2020-08-03,1,electronics,mobiles,<t>Near to mid range Perfection</t><b> Got i...
2,OnePlus Nord 5G,OnePlus,5.0,322,India,2020-08-04,1,electronics,mobiles,<t>Great price!</t><b> An amazing phone!</b>
3,OnePlus Nord 5G,OnePlus,5.0,243,India,2020-08-02,1,electronics,mobiles,<t>Beast in OnePlus.</t><b> Brilliant..</b>
4,OnePlus Nord 5G,OnePlus,5.0,109,India,2020-08-04,1,electronics,mobiles,<t>Changed to Nord from 6t</t><b> I was skept...
...,...,...,...,...,...,...,...,...,...,...
30607,Redmi Note 9 Pro,Redmi,2.0,0,India,2020-09-03,1,electronics,mobiles,<t>Great but not satisfied for me</t><b> Qual...
30608,Redmi Note 9 Pro,Redmi,2.0,0,India,2020-05-20,1,electronics,mobiles,<t>Not recommend</t><b> Not recommend</b>
30609,Redmi Note 9 Pro,Redmi,2.0,3,India,2020-06-29,0,electronics,mobiles,<t>WORST MARKETING TACTICS OF FLASH SALE OF RE...
30610,Redmi Note 9 Pro,Redmi,2.0,0,India,2020-04-26,0,electronics,mobiles,<t>Display retention issue</t><b> I am facing...
30611,Redmi Note 9 Pro,Redmi,2.0,0,India,2020-07-05,1,electronics,mobiles,<t>Camera quality is bad 👎</t><b> Front camer...

In [29]:
# Check for any null values again after transformations
for column_name in amazon_one_plus_reviews_db.columns.tolist():
  print(amazon_one_plus_reviews_db[column_name].isnull().any())

False
False
False
False
False
False
False
False
False
False

In [30]:
# Rename columns
amazon_one_plus_reviews_db.columns = ['product_name', 'product_company', 'review_rating', 'review_thumbsup_count', 'review_country', 'review_date', 'is_verfied_purchase', 'product_category', 'product_sub_category', 'review_descripiton']

# Reorder columns
new_order = ['product_name', 'product_company', 'review_descripiton', 'review_rating', 'review_thumbsup_count', 'review_country', 'review_date', 'is_verfied_purchase', 'product_category', 'product_sub_category']
amazon_one_plus_reviews_db = amazon_one_plus_reviews_db[new_order]

amazon_one_plus_reviews_db

,product_name,product_company,review_descripiton,review_rating,review_thumbsup_count,review_country,review_date,is_verfied_purchase,product_category,product_sub_category
0,OnePlus Nord 5G,OnePlus,<t>*Read before you buy!!*</t><b> Yea..pre-or...,5.0,721,India,2020-08-04,1,electronics,mobiles
1,OnePlus Nord 5G,OnePlus,<t>Near to mid range Perfection</t><b> Got i...,5.0,436,India,2020-08-03,1,electronics,mobiles
2,OnePlus Nord 5G,OnePlus,<t>Great price!</t><b> An amazing phone!</b>,5.0,322,India,2020-08-04,1,electronics,mobiles
3,OnePlus Nord 5G,OnePlus,<t>Beast in OnePlus.</t><b> Brilliant..</b>,5.0,243,India,2020-08-02,1,electronics,mobiles
4,OnePlus Nord 5G,OnePlus,<t>Changed to Nord from 6t</t><b> I was skept...,5.0,109,India,2020-08-04,1,electronics,mobiles
...,...,...,...,...,...,...,...,...,...,...
30607,Redmi Note 9 Pro,Redmi,<t>Great but not satisfied for me</t><b> Qual...,2.0,0,India,2020-09-03,1,electronics,mobiles
30608,Redmi Note 9 Pro,Redmi,<t>Not recommend</t><b> Not recommend</b>,2.0,0,India,2020-05-20,1,electronics,mobiles
30609,Redmi Note 9 Pro,Redmi,<t>WORST MARKETING TACTICS OF FLASH SALE OF RE...,2.0,3,India,2020-06-29,0,electronics,mobiles
30610,Redmi Note 9 Pro,Redmi,<t>Display retention issue</t><b> I am facing...,2.0,0,India,2020-04-26,0,electronics,mobiles
30611,Redmi Note 9 Pro,Redmi,<t>Camera quality is bad 👎</t><b> Front camer...,2.0,0,India,2020-07-05,1,electronics,mobiles

`amazon_one_plus_reviews_db` is ready to be loaded.

In [54]:
# Export the cleaned DataFrame to a JSON file
from google.colab import files

json_str = amazon_one_plus_reviews_db.to_json(orient='records')

with open('amazon_one_plus_reviews.json', 'w') as f:
    f.write(json_str)

# Download the JSON file to your local machine
files.download('amazon_one_plus_reviews.json')